## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('flooding', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/flooding-id-cache.cc',
        'model/flooding-dpd.cc',
        'model/flooding-packet.cc',
        'model/flooding-routing-protocol.cc',
        'helper/flooding-helper.cc',
        ]


    headers = bld(features='ns3header')
    headers.module = 'flooding'
    headers.source = [
        'model/flooding-id-cache.h',
        'model/flooding-dpd.h',
        'model/flooding-packet.h',
        'model/flooding-routing-protocol.h',
        'helper/flooding-helper.h',
        ]

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
